modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/xaidee/GloompersDelight/issues/"
license="The MIT License (MIT)"

[[mods]]
modId="gloompersdelight"
version="${file.jarVersion}"
displayName="Gloomper's Delight"
# updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/gloompers-delight"
logoFile="Gloomper's Delight.png"
logoBlur=false
itemIcon="undergarden:smog_vent"
configBackground="undergarden:textures/block/shiverstone_bricks.png"
credits='''
Thanks goes to Quek for their amazing dimension mod and Vectorwing's perfect food expansion mod!

Textures done by the very talented artist Frenderman!
'''
authors="Xaidee Quartz"
description='''
An addon to the Undergarden and Farmer's Delight mods.
'''

[[dependencies.gloompersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[46,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.gloompersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"